<?php
session_start();
if(isset($_SESSION["userinfo"])){	
	date_default_timezone_set("America/Mexico_City");
	include "cnx.php";		
	include "util_header.php";
	$conn = getConnection();
	
$allJS="";

getHeader("DashBoard", $allJS); 

?>
<!--
<div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1 style="font-size: 20px;">Unidades</h1>
                    <div><canvas data-bs-chart="{&quot;type&quot;:&quot;bar&quot;,&quot;data&quot;:{&quot;labels&quot;:[&quot;January&quot;,&quot;February&quot;,&quot;March&quot;,&quot;April&quot;,&quot;May&quot;,&quot;June&quot;],&quot;datasets&quot;:[{&quot;label&quot;:&quot;Graf1&quot;,&quot;backgroundColor&quot;:&quot;#18a558&quot;,&quot;borderColor&quot;:&quot;#18a558&quot;,&quot;data&quot;:[&quot;4500&quot;,&quot;5300&quot;,&quot;6250&quot;,&quot;7800&quot;,&quot;9800&quot;,&quot;15000&quot;]}]},&quot;options&quot;:{&quot;maintainAspectRatio&quot;:true,&quot;legend&quot;:{&quot;display&quot;:false},&quot;title&quot;:{}}}"></canvas></div>
                </div>
                <div class="col-md-6">
                    <h1 style="font-size: 20px;">Unidades</h1>
                    <div><canvas data-bs-chart="{&quot;type&quot;:&quot;radar&quot;,&quot;data&quot;:{&quot;labels&quot;:[&quot;January&quot;,&quot;February&quot;,&quot;March&quot;,&quot;April&quot;,&quot;May&quot;,&quot;June&quot;],&quot;datasets&quot;:[{&quot;label&quot;:&quot;Graf2&quot;,&quot;backgroundColor&quot;:&quot;#18a558&quot;,&quot;borderColor&quot;:&quot;#18a558&quot;,&quot;data&quot;:[&quot;4500&quot;,&quot;5300&quot;,&quot;6250&quot;,&quot;7800&quot;,&quot;9800&quot;,&quot;15000&quot;],&quot;fill&quot;:true}]},&quot;options&quot;:{&quot;maintainAspectRatio&quot;:true,&quot;legend&quot;:{&quot;display&quot;:false},&quot;title&quot;:{}}}"></canvas></div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1 style="font-size: 20px;">Unidades</h1>
                    <div><canvas data-bs-chart="{&quot;type&quot;:&quot;horizontalBar&quot;,&quot;data&quot;:{&quot;labels&quot;:[&quot;January&quot;,&quot;February&quot;,&quot;March&quot;,&quot;April&quot;,&quot;May&quot;,&quot;June&quot;],&quot;datasets&quot;:[{&quot;label&quot;:&quot;Graf3&quot;,&quot;backgroundColor&quot;:&quot;#18a558&quot;,&quot;borderColor&quot;:&quot;#18a558&quot;,&quot;data&quot;:[&quot;4500&quot;,&quot;5300&quot;,&quot;6250&quot;,&quot;7800&quot;,&quot;9800&quot;,&quot;15000&quot;]}]},&quot;options&quot;:{&quot;maintainAspectRatio&quot;:true,&quot;legend&quot;:{&quot;display&quot;:false},&quot;title&quot;:{}}}"></canvas></div>
                </div>
                <div class="col-md-6">
                    <h1 style="font-size: 20px;">Unidades</h1>
                    <div><canvas data-bs-chart="{&quot;type&quot;:&quot;pie&quot;,&quot;data&quot;:{&quot;labels&quot;:[&quot;January&quot;,&quot;February&quot;,&quot;March&quot;,&quot;April&quot;,&quot;May&quot;,&quot;June&quot;],&quot;datasets&quot;:[{&quot;label&quot;:&quot;Graf4&quot;,&quot;backgroundColor&quot;:[&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;],&quot;borderColor&quot;:[&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;,&quot;#18a558&quot;],&quot;data&quot;:[&quot;4500&quot;,&quot;5300&quot;,&quot;6250&quot;,&quot;7800&quot;,&quot;9800&quot;,&quot;15000&quot;]}]},&quot;options&quot;:{&quot;maintainAspectRatio&quot;:true,&quot;legend&quot;:{&quot;display&quot;:false},&quot;title&quot;:{}}}"></canvas></div>
                </div>
            </div>
        </div>
    </div>
!-->
<? 
getFooter(); 
}else{
	header("Location: .");
}
?>