<?
session_start();
if(isset($_SESSION["userinfo"])){
	$nscript = pathinfo($_SERVER['PHP_SELF'], PATHINFO_FILENAME);	
	$mod = explode("_",$nscript);
	$modulo = $mod[0]."_".$mod[1];
	$modfrm = $mod[2];
	$form = $modulo."/".$modfrm.".php";
	//echo "nscript: ".$nscript." module: ".$modulo." form: ".$form;
	date_default_timezone_set("America/Mexico_City");
	include "cnx.php";			
	include "util_list.php";
	$conn = getConnection();
	$usr = $_SESSION["userinfo"]["username"];
	$cia = $_SESSION["compania"]["idCompania"];
	$aut=ValPerPag($usr,$modulo);
	//$aut=1;
if ($aut == 1) {
	include "util_frame.php";
	
	$tipo 		= isset($_SESSION[$modulo]["tipos"])?unserialize($_SESSION[$modulo]["tipos"]):null;
	$idTipo 	= !is_null($tipo)?$tipo["cve_reg"]:"";
	$tiptrj		= !empty($tipo)?$tipo["cve_tip"]:"";
	$destip		= !empty($tipo)?$tipo["des_tip"]:"- Seleccione Tipo -";
	$porcentaje = !is_null($tipo)?$tipo["pct_desc"]:"";
	$fecefe 	= !empty($tipo)?date("Y-m-d",strtotime($tipo["fec_efe"])):"";	
	$status 	= !is_null($tipo)?$tipo["stt_pct"]:"";
	$maxmov		= !empty($tipo)?$tipo["maxmov"]:"- Seleccione Pases -";
	$timeout	= !empty($tipo)?$tipo["timeout"]:"- Seleccione Tiempo -";
	//echo "tipos: ".print_r($tipo)." pct: ".$porcentaje;

	

$jsActivo = "
<script type='text/javascript'>function setActivo(o){
	if(document.getElementById('status').value=='A'){
		document.getElementById('status').value='I';
		document.getElementById('onoff').src='http://cnf.prepay.com.mx/assets/img/off.png';
	}else{
		document.getElementById('status').value='A';
		document.getElementById('onoff').src='http://cnf.prepay.com.mx/assets/img/on.png';
	}
}</script>";

$allJS="";
$allJS .= $jsActivo;
	
getHeaderFrm("Tipos Tarjeta", $allJS); 
?>
<form action = "<? echo $form; ?>" method="POST" >
<input type="hidden" id="idTipo" name="idTipo" value="<?php echo $idTipo; ?>" />
	<div class="modal-body">
	<div class="row">
		<div class="col"><strong>Tipo</strong>							
		<select style="width: 100%;" id="tipo" name="tipo" required >
		<option value="<? echo $tiptrj; ?>"><? echo $destip; ?></option>
		<?
		$arrDat = getDataFromTable($conn,"select cve_tip, des_tip from cat_tip_trj where cve_tip not in (select cve_tip from sis_pct_tip_cia where cve_cia='$cia' and stt_pct='A')");
		foreach($arrDat as $dat){
		?>
		<option value="<? echo $dat["cve_tip"]; ?>"><? echo $dat["des_tip"]; ?></option>
		<? } ?>
		</select>					
		</div>		
			<div class="col"><strong>Porcentaje Desc</strong><input type="text" style="width: 100%;" id="porcentaje" name="porcentaje" value="<? echo $porcentaje ?>" required ></div>
			<div class="col"><strong>Pases x Dia</strong>
				<select style="width: 100%;" id="maxmov" name="maxmov" required >
					<option value="<? echo $maxmov; ?>"><? echo $maxmov; ?></option>
					<?
					for ($i=1; $i <= 100; $i++){
					?>
					<option value="<? echo $i; ?>"><? echo $i; ?></option>
					<? } ?>
				</select>
			</div>
		</div>
		<div class="row">
			<div class="col"><strong>Tiempo / Pase (min)</strong>
				<select style="width: 100%;" id="timeout" name="timeout" required >
					<option value="<? echo $timeout; ?>"><? echo $timeout; ?></option>
					<?
					for ($j=0; $j <= 60; $j++){
					?>
					<option value="<? echo $j; ?>"><? echo $j; ?></option>
					<? } ?>
				</select>
			</div>
			<div class="col"><strong>Fecha Efectiva</strong><input type="date" style="width: 100%;" id="fecefe" name="fecefe" value="<? echo $fecefe; ?>" required></div>
			<div class="col"><strong>Activa</strong>
			<p><img id = "onoff" src='http://cnf.prepay.com.mx/assets/img/<?php echo empty($status)?"inter":($status=="I"?"off":"on"); ?>.png' onclick = "setActivo(this)" height='40' /></p>
			<input id= "status" name= "status" type="hidden" value="<?php echo $status; ?>" />
			</div>
		</div>		
	</div>
	<p class="text-center" style="background-color: #ff6b00;color: rgb(255,255,255);" id="mensajeacciontipo" ><? echo $_SESSION["tipos"]["message"];?></p>
	<div class="modal-footer" style="height: 65px;">
		<?php
		if(empty($idTipo)){
			$transaction = "Agregar";
		}else{
			$transaction = "Actualizar";
		}						
		?>
		<p class="text-right"><input class="btn btn-success" style="margin: 9px;margin-left: 5px;width: 100%;" name="btn<?php echo $transaction; ?>" type="submit" value="<?php echo $transaction; ?>"></p>
		</div>
	</div>
</form>
<div class="col-md-12 search-table-col" style="margin: 10px 0px 0px;">
     <div class="table-responsive table-bordered table table-hover table-bordered results">
         <table class="table table-bordered table-hover">
             <thead class="bill-header cs" style="color: rgb(29,42,159);">
                 <tr style="color: rgb(229,230,242);background-color: rgb(24,165,88);">                     
                     <th id="trs-hd" class="col-lg-2">Tipo</th>
                     <th id="trs-hd" class="col-lg-3">Porcentaje Descuento</th>
					 <th id="trs-hd" class="col-lg-3">Fecha Efectiva</th>					 
                     <th id="trs-hd" class="col-lg-2">Acciones</th>
                 </tr>
             </thead>
             <tbody>
                 <tr class="warning no-result">
                     <td colspan="12"><i class="fa fa-warning"></i>&nbsp; No hay Resultados !!!</td>
                 </tr>
			<?
			$sql="select a.cve_reg,b.des_tip,a.pct_desc,a.fec_efe,a.stt_pct from 
				 sis_pct_tip_cia a, cat_tip_trj b
				 where a.cve_tip=b.cve_tip
				 and cve_cia='$cia'";
			$arrDat = getDataFromTable($conn,$sql);
			foreach($arrDat as $dat){
			?>
                <tr>
                  <td><? echo $dat["des_tip"] ?></td>
                  <td><? echo $dat["pct_desc"] ?></td>				
				  <td><? echo $dat["fec_efe"] ?></td>
				<? echo "<td data-label='...' ><img src='http://cnf.prepay.com.mx/assets/img/".($dat["stt_pct"]=="I"?"off":"on").".png' height='40' />
				<button class='btn btn-success' style='margin-left: 5px;' type='submit' onclick = \"location.href = '$modulo/$modfrm.php?u=".$dat["cve_reg"]."';\"'><i class='fa fa-edit' style='font-size: 15px;' ></i></button>				
				</td>";?>                            
                 </tr>
			<? } ?>
             </tbody>
         </table>
     </div>
 </div>
<?
if(isset($_SESSION[$modfrm])){
	unset($_SESSION[$modfrm]);
}
getFooterFrm(); 
} else {
	header("Location: ./main.phtml");
}
}else{
	header("Location: .");
}
?>