<?php
session_start();
if(isset($_SESSION["userinfo"])){
	$nscript = pathinfo($_SERVER['PHP_SELF'], PATHINFO_FILENAME);
	date_default_timezone_set("America/Mexico_City");
	include "cnx.php";			
	include "util_list.php";
	require "$nscript/dispositivos.php";
	$conn = getConnection();
	$usr = $_SESSION["userinfo"]["username"];
	$aut=ValPerPag($usr,$nscript);
	//echo "nscript: ".$nscript." usr: ".$usr." aut: ".$aut;

if ($aut == 1) {
	include "util_header.php";
	
	$dispositivo		= isset($_SESSION[$nscript]["dispositivos"])?unserialize($_SESSION[$nscript]["dispositivos"]):null;
	//echo "nscript: ".$nscript." dispositivo: ".$dispositivo; 	
	$idDispositivo	= !is_null($dispositivo)?$dispositivo->idDispositivo:"";
	$imei			= !is_null($dispositivo)?$dispositivo->imei:"";
	$desDispositivo = !is_null($dispositivo)?$dispositivo->desDispositivo:"";
	$compania		= !is_null($dispositivo)?$dispositivo->compania:"";	
	$status			= !is_null($dispositivo)?$dispositivo->status:"";
	//echo "id dis: ".$idDispositivo;
		
$jsModal1 = "
		<script type='text/javascript'>
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>";
$jsActivo = "
<script type='text/javascript'>function setActivo(o){
			if(document.getElementById('status').value=='A'){
				document.getElementById('status').value='I';
				document.getElementById('onoff').src='http://cnf.prepay.com.mx/assets/img/off.png';
			}else{
				document.getElementById('status').value='A';
				document.getElementById('onoff').src='http://cnf.prepay.com.mx/assets/img/on.png';
			}
		}</script>";

$allJS="";
$allJS .= isset($_SESSION[$nscript]["message"])?$jsModal1:"";
$allJS .= $jsActivo;


getHeader("Dispositivos", $allJS); 

?>

<div>
        <div class="container">
		<form action = "<?php echo $nscript; ?>/" method="POST" >
		<input type="hidden" name="idDispositivo" value="<?php echo $idDispositivo; ?>" />
            <div class="row">
                <div class="col-md-3"><strong>IMEI</strong><input type="text" style="width: 100%;" maxlength="20" name="imei" value="<?php echo $imei; ?>"></div>
                <div class="col"><strong>Descripción</strong><input type="text" style="width: 100%;" name="desdispositivo" value="<?php echo $desDispositivo; ?>"></div>
                <div class="col"><strong>Compañia</strong>
				<select style="width: 100%;" name="compania">
				<option value="" selected="">- Compañia -</option>
				<?
				$arrDat = listActiveCompanies($usr);
				foreach($arrDat as $dat)
				echo "<option value='".$dat["cve_cia"]."' ".($compania==$dat["cve_cia"]?"selected":"").">".$dat["des_cia"]."</option>";
				?>								
				</select>
				</div>
                <div class="col-md-3"><strong style="width: 100%;">Activo</strong>
				<p><img id = "onoff" src='http://cnf.prepay.com.mx/assets/img/<?php echo empty($status)?"inter":($status=="I"?"off":"on"); ?>.png' onclick = "setActivo(this)" height='40' /></p>
				<input id= "status" name= "status" type="hidden" value="<?php echo $status; ?>" />		
				</div>
			</div>
		</div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
				<?php
				if(empty($idDispositivo)){
					$transaction = "Agregar";
				}else{
					$transaction = "Actualizar";
				}						
				?>
				<p class="text-right"><input class="btn btn-success" style="margin: 9px;margin-left: 5px;width: 100%;" name="btn<?php echo $transaction; ?>" type="submit" value="<?php echo $transaction; ?>"></p></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
	</form>
</div>
    <div class="container">
        <div class="col-md-12 search-table-col" style="margin: 10px 0px 0px;">
            <div class="form-group pull-right col-lg-4"><input type="text" class="search form-control" placeholder="Buscar Dispositivos"></div><span class="counter pull-right"></span>
            <div class="table-responsive table-bordered table table-hover table-bordered results">
                <table class="table table-bordered table-hover">
                    <thead class="bill-header cs" style="color: rgb(29,42,159);">
                        <tr style="color: rgb(229,230,242);background-color: rgb(24,165,88);">
                            <th id="trs-hd" class="col-lg-1">Folio</th>
                            <th id="trs-hd" class="col-lg-2">imei</th>
                            <th id="trs-hd" class="col-lg-3">descripcion</th>
                            <th id="trs-hd" class="col-lg-2">compañia</th>
                            <th id="trs-hd" class="col-lg-2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="warning no-result">
                            <td colspan="12"><i class="fa fa-warning"></i>&nbsp; No hay Resultados !!!</td>
                        </tr>
						<?						
						$arrDat = listAllDevices($usr);
						foreach($arrDat as $dat){
						?>
                        <tr>
                            <td><? echo $dat["cve_dis"] ?></td>
							<td><? echo $dat["imei"] ?></td>
							<td><? echo $dat["des_dis"] ?></td>
							<td><? echo $dat["des_cia"] ?></td>
                            <? echo "<td data-label='...' ><img src='http://cnf.prepay.com.mx/assets/img/".($dat["stt_dis"]=="I"?"off":"on").".png' height='40' />
							<button class='btn btn-success' style='margin-left: 5px;' type='submit' onclick = \"location.href = '$nscript/?u=".$dat["cve_dis"]."';\"'><i class='fa fa-edit' style='font-size: 15px;' ></i></button>
							<button class='btn btn-danger' style='margin-left: 5px;' type='submit'><i class='fa fa-trash' style='font-size: 15px;'></i></button>
							</td>";?>                            
                        </tr>
						<? } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
	
	<div>
		<div class="modal fade" role="dialog" tabindex="-1" id="myModal">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h4>Gestión de Dispositivos</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>
					<div class="modal-body">
						<p class="text-center text-muted"><?php echo $_SESSION[$nscript]["message"]; ?> </p>
					</div>
					<div class="modal-footer"><button class="btn btn-primary" type="button" data-dismiss="modal">Entendido</button></div>
				</div>
			</div>
		</div>
	</div>



<?
if(isset($_SESSION[$nscript])){
	unset($_SESSION[$nscript]);
} 
getFooter(); 
} else {
	header("Location: ./main.phtml");
}
}else{
	header("Location: .");
}
?>
