<?php
session_start();
if(isset($_SESSION["userinfo"])){
	$nscript = pathinfo($_SERVER['PHP_SELF'], PATHINFO_FILENAME);	
	date_default_timezone_set("America/Mexico_City");
	include "cnx.php";			
	include "util_list.php";
	require "$nscript/recargas.php";
	$conn = getConnection();
	$fecact = date("Y-m-d");
	$usr = $_SESSION["userinfo"]["username"];
	$aut=ValPerPag($usr,$nscript);
	$lim = 100;
	$min = 0;
	//echo "nscript: ".$nscript." usr: ".$usr." aut: ".$aut;	
if ($aut == 1) {	
	include "util_header.php";
	
	$compania		= isset($_SESSION[$nscript]["compania"])?unserialize($_SESSION[$nscript]["compania"]):null;
	//echo "nscript: ".$nscript." compania: ".$compania; 
	//$idCompania		= !is_null($compania)?$compania->idCompania:"";
	if ($_POST){
	$_SESSION["admrec"]["ptovta"] = $_POST['puntoventa'];
	$_SESSION["admrec"]["firec"] = $_POST['fecini'];
	$_SESSION["admrec"]["ffrec"] = $_POST['fecfin'];	
	}
	
    if ($_GET){
	$p = $_GET["p"];	
	$p1 = $p-1;
	$min = $p1*$lim;
	}
	
	$puntoventa = $_SESSION["admrec"]["ptovta"];
	$fecini = $_SESSION["admrec"]["firec"];
	$fecfin	= $_SESSION["admrec"]["ffrec"];	
	//echo "ptovta: ".$puntoventa. " fi: ".$fecini." ff: ".$fecfin;
	//echo "p: ".$p."</br>";


$jsMapaModal="<script type='text/javascript'> 
				function showMapa(uni,lat,lon){
				$('#MapaModal').modal('show');					
				escribiriframe(uni,lat,lon)
				}				
									
				function escribiriframe(uni,lat,lon){
				console.log(uni);	
				var frm='<iframe id=\"idmapfrm\" allowfullscreen=\"\" frameborder=\"0\" src=\"mng_map_reg.phtml?uni='+uni+'&lat='+lat+'&lon='+lon+'\" width=\"100%\" height=\"400\"></iframe>';
				console.log(frm);
				document.getElementById('idmapfrm').innerHTML=frm; 
				} 
			</script>";
			  
$allJS="";
$allJS .= $jsMapaModal;
getHeader("Recargas", $allJS, $conn); 

?>
	<div>
        <div class="container">
		<form action = "mng_recargas.phtml" method="POST" >
            <div class="row">
                <div class="col-md-3"><strong>Punto de Venta</strong>
				<select style="width: 100%;" name="puntoventa">
				<option value="" selected="">- Punto de Venta -</option>
				<?
				$arrTer = listActiveSalePoints($usr);
				foreach($arrTer as $ter)
				echo "<option value='".$ter["cve_rel"]."' ".($puntoventa==$ter["cve_rel"]?"selected":"").">".$ter["dato"]."</option>";				
				?>								
				</select>
				</div>
                <div class="col-md-3"><strong>Fecha Inicio</strong><input type="date" id="fecini" name="fecini" style="width: 100%;" value="<? echo $fecini==""?$fecact:$fecini?>" required ></div>
				<div class="col-md-3"><strong>Fecha Fin</strong><input type="date" id="fecfin" name="fecfin" style="width: 100%;" value="<? echo $fecfin==""?$fecact:$fecfin?>" required ></div>
				<div class="col-md-3"></div>
			</div>		
            <div class="row">
                <div class="col-md-3">
				<button class="btn btn-primary" type="submit" style="background-color: rgb(24,165,88);width: 100%;margin: 5px;">Buscar</button>
				</div>
                <div class="col-md-3">				
				<a href="recexcel.phtml" target="_blank" class="btn btn-primary" style="margin: 5px;background-color: rgb(173,173,173);width: 100%;">Exportar Excel</a>
				</div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
            </div>
		</form>
        </div>
    </div>
    <div class="container">
        <div class="col-md-16 search-table-col" style="margin: 10px 0px 0px;">
            <div class="form-group pull-right col-lg-4"><input type="text" class="search form-control" placeholder="Buscar Recarga"></div><span class="counter pull-right"></span>
            <div class="table-responsive table-bordered table table-hover table-bordered results" style="font-size: 10px;">
                <table class="table table-bordered table-hover">
                    <thead class="bill-header cs" style="color: rgb(29,42,159);">
                        <tr style="color: rgb(229,230,242);background-color: rgb(24,165,88);">
                            <th id="trs-hd" class="col-lg-1" style="width: 50px;">FOLIO</th>
                            <th id="trs-hd" class="col-lg-2">PUNTO VENTA</th>
							<th id="trs-hd" class="col-lg-2">LINEA</th>
							<th id="trs-hd" class="col-lg-2">COMPAÑIA</th>
                            <th id="trs-hd" class="col-lg-3" style="width: 60px;">MONTO</th>
                            <th id="trs-hd" class="col-lg-2" style="width: 50px;">MON.</th>
                            <th id="trs-hd" class="col-lg-2" style="width: 60px;">TIPO MOV.</th>
                            <th id="trs-hd" class="col-lg-2" style="width: 110px;">CLAVE TARJETA</th>
                            <th id="trs-hd" class="col-lg-2">TIPO TARJETA</th>
                            <th id="trs-hd" class="col-lg-2" style="width: 70px;">SALDO ANT.</th>
                            <th id="trs-hd" class="col-lg-2">FECHA RECARGA</th>
                            <th id="trs-hd" class="col-lg-2">USUARIO</th>
                            <th id="trs-hd" class="col-lg-2" style="width: 160px;">IMEI</th>
							<th id="trs-hd" class="col-lg-2" style="width: 60px;">Ubic.</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="warning no-result">
                            <td colspan="16"><i class="fa fa-warning"></i>&nbsp; No hay Resultados !!!</td>
                        </tr>
						<?											
						//$_SESSION['userinfo']['sqlRec'] = $sqlRec;						
						$arrRec1 = listAllRecharge($usr,$puntoventa,$fecini,$fecfin,"","");
						$cntrec = count($arrRec1);
						//echo "rec".$cntrec;						
						$arrRec2 = listAllRecharge($usr,$puntoventa,$fecini,$fecfin,$min,$lim);
						foreach($arrRec2 as $rec){
							$dat = $rec["des_ter"];							
						?>
                        <tr style="font-size: 12px;">
                            <td><? echo $rec["cve_reg"] ?></td>
                            <td><? echo $rec["des_ter"] ?></td>
							<td><? echo $rec["des_lin"] ?></td>
							<td><? echo $rec["des_cia"] ?></td>
                            <td>$<? echo $rec["monto"] ?></td>
							<td><? echo $rec["moneda"] ?></td>
							<td><? echo $rec["des_mov"] ?></td>
							<td><? echo $rec["cve_trj"] ?></td>
							<td><? echo $rec["des_tip"] ?></td>
							<td>$<? echo $rec["saldo"] ?></td>
							<td><? echo $rec["fec_rec"] ?></td>
							<td><? echo $rec["usr_cap"] ?></td>
							<td><? echo $rec["imei"] ?></td>
							<? if ($rec["latitud"] == ""){ ?>
							<td><img src="http://cnf.prepay.com.mx/assets/img/process_stop.png" width="32" height="32"></td>
							<? } else { ?>
							<!--<td><a href="#" onClick="window.open('http://maps.google.com/maps?q=<? //echo $rec["latitud"] ?>,<? //echo $rec["longitud"] ?>&zoom=1', 'Ubicacion', 'width=600, height=400')" ><img src="http://cnf.prepay.com.mx/assets/img/maps_64dp.png" width="32" height="32"></a></td>!-->
							<td><a href="#" onClick="showMapa(<? echo $rec["cve_reg"] ?>,<? echo $rec["latitud"] ?>,<? echo $rec["longitud"] ?>)"><img src="http://cnf.prepay.com.mx/assets/img/maps_64dp.png" width="32" height="32"></a></td>
							<? } ?>
                        </tr>
						<? } ?>
                    </tbody>
					<? if ($cntrec > $lim){										
					$pagind = ceil($cntrec / $lim);
					$ant = $p-1;
					$sig = $p+1;
					$dec = 10;
					$ini = 1;
					if ($ant <= 1){
						$ant=1;
					}
					if ($sig >= $pagind){
						$sig=$pagind;
					}
					if ($p >= $dec){
						//echo "p: ".$p." $dec: ".$dec;
						$ini = $p;
						$dec = $dec+$p;
					}
					?>
					<tfoot>
						<tr>
							<td colspan="2">	
							<p>Pagina <?  echo $p==""?1:$p ?> de <? echo $pagind; ?></p>
							</td>
							<td colspan="14" style="font-size: 12px;">	
							 <nav>
                                    <ul class="pagination">									    
                                        <li class="page-item"><a class="page-link" href="?p=1" aria-label="Principio"><span aria-hidden="true">«</span></a></li>
										<li class="page-item"><a class="page-link" href="?p=<? echo $ant; ?>" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
										<? for ($i=$ini; $i<=$pagind; $i++) {?>
                                        <li class="page-item"><a class="page-link" href="?p=<? echo $i; ?>"><? echo $i; ?></a></li>
										<? 										
										if ($i >= $dec){
											$j=$i+9;		
												if ($j >= $pagind){
													$j=$pagind;
										?>
										<li class="page-item"><a class="page-link" href="?p=<? echo $j; ?>"><? echo $j; ?></a></li>										
										<? 
												}
												$i=$j;
											}											
										} 
										?>
                                        <li class="page-item"><a class="page-link" href="?p=<? echo $sig; ?>" aria-label="Next"><span aria-hidden="true">»</span></a></li>
										<li class="page-item"><a class="page-link" href="?p=<? echo $pagind; ?>" aria-label="Fin"><span aria-hidden="true">»</span></a></li>
                                    </ul>
                                </nav>							
							</td>							
						</tr>
					</tfoot>
					<? } ?>
                </table>
            </div>
        </div>
    </div>
	<div class="modal fade" role="dialog" tabindex="-1" id="MapaModal">
            <div class="modal-dialog" role="document" style="max-width:700px;">
                <div class="modal-content">
                    <div class="modal-header" style="height: 49px;background-color: #ededed;">
                        <h4>Punto de recarga <? echo $dat; ?></h4>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
					</div>
					<div id="idmapfrm"></div>
				</div>
			</div>
	</div>

<?php

getFooter(); 
} else {
	header("Location: ./main.phtml");
}
}else{
	header("Location: .");
}
?>