<?php
if(isset($_POST["param_location"])){
	include 'cnx.php';
	$conn = getConnection();
	$param = $_POST["param_location"];
	$loc = explode(",", $param);
	$lat = $loc[0];
	$lon = $loc[1];
	//echo "Aqui va el codigo de insert".$param;
	$sql = "INSERT INTO sis_trk_uni values (NULL,1,1,1,1,$lat,$lon,'".date("Y-m-d H:i:s")."','356021081495810')";
	
	$stmt = $conn->prepare($sql);			
	if($stmt->execute()===TRUE){
		echo "OK";
	}
}else{
	
?>

<!DOCTYPE html>
<html>
<META HTTP-EQUIV="REFRESH" CONTENT="30;URL=https://dev.coproit.com/ocetech/mng_sembrado.phtml">
<head>
<script src="assets/js/jquery.min.js"></script>
<script>
	$.ajaxSetup({'beforeSend' : function(xhr) {try{xhr.overrideMimeType('text/html; charset=iso-8859-1');}catch(e){}	}}); 
		function obtener(){
			navigator.geolocation.getCurrentPosition(mostrar, gestionarErrores);
		}
		function mostrar(posicion){
			document.getElementById("latitud").value =""+posicion.coords.latitude;
			document.getElementById("longitud").value =""+posicion.coords.longitude;
			var location = posicion.coords.latitude+","+posicion.coords.longitude;
			if(posicion.coords.latitude !="" && posicion.coords.longitude !=""){
				$.post('mng_sembrado.phtml',{param_location:location}).done(function(data){ $('#tempdiv').html(data);})
			}
		}
		function gestionarErrores(error){
		/*	var xmlhttp;
			
			if (window.XMLHttpRequest){// code for IE7+, Firefox, Chrome, Opera, Safari
				xmlhttp=new XMLHttpRequest();
			}else{// code for IE6, IE5
				xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
			}
			xmlhttp.open("POST","notifylocation.php",true);
			xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
			xmlhttp.send("q="+error.code);
		*/
			//alert('Error: '+error.code+' '+error.message+ '\n\nPor favor habilite la opción permitir compartir ubicación física');
			alert('Para registrar actividades es necesario habilitar el GPS.');
			
		}
</script>

<body onload="obtener()">


<form method="post" action="registro_actividades.php">
		<h1 class="text-center text-primary" style="font-family:Electrolize, sans-serif;">Registro de actividades</h1>
		<input type="text" name="latitud" id="latitud" />
		<input type="text" name="longitud" id="longitud" />
</form>
<div type="hidden" id="tempdiv" />
</body>
</html>
<?php
	}
?>