<?
session_start();
if(isset($_SESSION["userinfo"])){
	include "/home/envdtsme/cnf.prepay.com.mx/credentials/google/GLOBAL_API_KEY.php";
	include "cnx.php";	
	include "util_list.php";
	$usr = $_SESSION['userinfo']['username'];
	$uni = $_GET['uni'];
	$lat = $_GET['lat'];
	$lon = $_GET['lon'];	
	//$zoom= $_GET['zoom'];
	//echo "uni: ".$uni;
	$googleKeys = new GoogleConstantsKeys();
	$apiKey = $googleKeys::GEOLOCATION_API_KEY;
	/*$content = "<div id='content".$uni."'>
							<div id='siteNotice'>
							</div>
							<h1 id='firstHeading' class='firstHeading'>$eco</h1>
							<div id='bodyContent'>
							<p>prueba de contenido</p>
							</div>
							</div>";*/
	//echo "cont: ".$content;

//$arrRec = listTracking($usr,$uni,$fi,$ff);												

?>
<!DOCTYPE html>
<html>
  <head>
    <title>Registro</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $apiKey; ?>&callback=initMap" async defer></script>
    <style type="text/css">
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }

      /* Optional: Makes the sample page fill the window. */
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
    <script>
      "use strict";

      // This example displays a marker at the center of Australia.
      // When the user clicks the marker, an info window opens.
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: {lat: <? echo $lat; ?>, lng: <? echo $lon; ?>}		  
        }); 
		var image = {          
		  url: 'http://cnf.prepay.com.mx/assets/img/puntocobro.png',          
		  size: new google.maps.Size(24, 24),                    
          origin: new google.maps.Point(0, 0),          
		  anchor: new google.maps.Point(0, 24)          
        };
		var shape = {
          coords: [1, 1, 1, 20, 18, 20, 18, 1],
          type: 'poly'
        };				
	  //console.log(<? echo $eco; ?>);		
      /*  var contentString = <? echo "\"".$content."\""; ?>;			
		
        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });*/
        var marker = new google.maps.Marker({
		  position: {lat: <? echo $lat; ?>, lng: <? echo $lon; ?>},
		  //position: {lat: 19.4675655, lng: -99.1036529},
          map: map,
          icon: image,
          shape: shape,
          title: <? echo "'".$uni."'"; ?>,
          zIndex: 0
        });
        /*marker.addListener("click", () => {
          infowindow.open(map, marker);
        });*/
	}
    </script>
  </head>
  <body>
    <div id="map"></div>
  </body>
</html>
<?
}
?>